name: quran_project
description: A premium Islamic app with Quran player, Qibla, and Khatmah calculator.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  provider: ^6.0.5
  font_awesome_flutter: ^10.6.0
  just_audio: ^0.9.36
  percent_indicator: ^4.2.3
  intl: ^0.19.0
  flutter_qibla: ^2.0.0
  shared_preferences: ^2.2.2
  adhan: ^2.1.0
  geolocator: ^11.0.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
    - family: AmiriQuran
      fonts:
        - asset: assets/fonts/AmiriQuran.ttf
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic-Regular.ttf
        - asset: assets/fonts/NotoSansArabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansArabic-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansArabic-SemiBold.ttf
          weight: 600

